export const scheduleData = [
    {
        num: 1,
        topic: "Introduction and welcome",
        presenter: "J C Mohan/ Vinayak Agrawal",
        timing: "2.50 -3.00 pm",
    },
    {
        num: 2,
        topic: "Acute MR in ACS",
        presenter: "K K Kapur",
        timing: "3.00 -3.15 pm",
    },
    {
        num: 3,
        topic: "Unusual case of HFrEF",
        presenter: "Madhu Shukla",
        timing: "3.15 -3.30 pm",
    },
    {
        num: 4,
        topic: "Malignant MVP",
        presenter: "J C Mohan",
        timing: "3.30 -3.45 pm",
    },
    {
        num: 5,
        topic: "Post PCI stenting and fever",
        presenter: "Sameer Srivastava ",
        timing: "3.45 –4.00 pm",
    },
    {
        num: 6,
        topic: "A curious case of complicated MI in Covid-19",
        presenter: "Vinayak Agrawal",
        timing: "4.00 -4.15 pm",
    },
    {
        num: 7,
        topic: "Intervention in Tricuspid valve pathology",
        presenter: "Satish Govind",
        timing: "4.15 -4.30 pm",
    },
    {
        num: 8,
        topic: "Stress Echo in valvular heart disease",
        presenter: "Debika Chaterjee",
        timing: "4.30 -4.45 pm",
    },
    {
        num: 9,
        topic: "3D Echo in TAVR",
        presenter: "Sanjay Mittal",
        timing: "4.45 – 5.00 pm  ",
    },
    {
        num: 10,
        topic: "Strain Imaging in aortic stenosis : has its time arrived? ",
        presenter: "Manish Bansal",
        timing: "5.00 -5.15 pm  ",
    },
    {
        num: 11,
        topic: "Unusual case of HFpEF",
        presenter: "J C Mohan",
        timing: "5.15 -5.30 pm  ",
    },
    {
        num: 12,
        topic: "A unique case of congenital heart disease",
        presenter: "S Radhakrishnan",
        timing: "5.30 -5.45 pm  ",
    },
    {
        num: 13,
        topic: "Post chemotherapy HF:  an unusual case  ",
        presenter: "Vinayak Agrawal",
        timing: "5.45 – 6.00 pm  ",
    },
    {
        num: 14,
        topic: "An  unusual cardiac mass ",
        presenter: "Simmi Manocha",
        timing: "6.00 -6.15 pm  ",
    },
    {
        num: 15,
        topic: "Non Compaction vserus Hypertrabeculations",
        presenter: "Nitin Burkule",
        timing: "6.15 -6.30 pm  ",
    },
    {
        num: 16,
        topic: "Low flow , Low Gradient Aortic stenosis ",
        presenter: "C K Ponde",
        timing: "6.30 -6.45 pm  ",
    },
    {
        num: 17,
        topic: "Interesting cases of Diastology ",
        presenter: "Shantanu Sengupta",
        timing: "6.45 – 7.00 pm  ",
    },
    {
        num: 18,
        topic: "A case of Constrictive pericarditis ",
        presenter: "K Raghu",
        timing: "7.00  – 7.15 pm",
    },
    {
        num: 19,
        topic: "Amyloidosis : Multimodality Imaging is the rule ",
        presenter: "Nitin Burkule",
        timing: "7.15 – 7.30 pm ",
    },
    {
        num: 20,
        topic: "A young man with CHB (Sarcoid)",
        presenter: "J C Mohan",
        timing: "7.30 – 7.45 pm",
    },
    {
        num: 21,
        topic: "Tamponade physiology : subtle and the obvious ",
        presenter: "U P Singh",
        timing: "7.45 – 8.00 pm",
    },
    {
        num: 22,
        topic: "An unusual case of Pulmonary HT",
        presenter: "Rahul Mehrotra",
        timing: "8.00  – 8.15 pm    ",
    }
]
